import os
import sys
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from app.models import MenuItem

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    raise ValueError("DATABASE_URL is missing in backend/.env!")

engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(bind=engine)
db = SessionLocal()

RAIDAN_EXACT_MENU = [
    # 1. Mandi
    {"name": "Chicken Mandi", "cat": "Mandi", "price": 290.0},
    {"name": "Chicken Madghuth", "cat": "Mandi", "price": 290.0},
    {"name": "Mutton Mandi", "cat": "Mandi", "price": 430.0},
    {"name": "Mutton Madghuth", "cat": "Mandi", "price": 430.0},
    {"name": "Mutton Madfoona", "cat": "Mandi", "price": 440.0},
    {"name": "Mutton Madfoona With Rice", "cat": "Mandi", "price": 610.0},
    {"name": "Mutton Kabsa", "cat": "Mandi", "price": 430.0},

    # 2. Rice
    {"name": "Mandi Rice", "cat": "Rice", "price": 170.0},
    {"name": "Kabsa Rice", "cat": "Rice", "price": 170.0},
    {"name": "Ghee Rice", "cat": "Rice", "price": 135.0},
    {"name": "White Rice", "cat": "Rice", "price": 85.0},
    {"name": "Curd Rice", "cat": "Rice", "price": 115.0},

    # 3. Mandi Family Pack[cite: 5]
    {"name": "Full Mutton 5kg with 10 Rice", "cat": "Mandi Family Pack", "price": 12600.0},
    {"name": "Malbhi with Rice (4 Person)", "cat": "Mandi Family Pack", "price": 1150.0},
    {"name": "Alfaham with Rice (4 Person)", "cat": "Mandi Family Pack", "price": 1150.0},
    {"name": "Pepper BBQ with Rice (4 Person)", "cat": "Mandi Family Pack", "price": 1150.0},
    {"name": "Chi-Mandi Authentic (4 Person)", "cat": "Mandi Family Pack", "price": 1150.0},
    {"name": "Mandi Chi-Tandoori Family (4 Person)", "cat": "Mandi Family Pack", "price": 1150.0},
    {"name": "Mandi Chi-Alfaham Special", "cat": "Mandi Family Pack", "price": 1250.0},
    {"name": "Mandi Mutton Leg with 5 Rice", "cat": "Mandi Family Pack", "price": 2310.0},
    {"name": "Mandi Grill", "cat": "Mandi Family Pack", "price": 1150.0},
    {"name": "Mandi Chicken Kabab (2 Person)", "cat": "Mandi Family Pack", "price": 610.0},
    {"name": "Mandi Fish Fresh (Seasonal)", "cat": "Mandi Family Pack", "price": 0.0},
    {"name": "Mandi Prawns Fresh (Seasonal)", "cat": "Mandi Family Pack", "price": 0.0},
    {"name": "Mandi Prawns Frozen (4 Person)", "cat": "Mandi Family Pack", "price": 0.0},
    {"name": "Mutton Raan Mandi (3 Person)", "cat": "Mandi Family Pack", "price": 1420.0},
    {"name": "Chicken Mandi (2 Person)", "cat": "Mandi Family Pack", "price": 610.0},
    {"name": "Mix Mandi (4 Person)", "cat": "Mandi Family Pack", "price": 2200.0},
    {"name": "Mix Mandi (2 Person)", "cat": "Mandi Family Pack", "price": 1250.0},

    # 4. Arabian Style Chicken[cite: 5]
    {"name": "Malbhi Barbecue (Quarter)", "cat": "Arabian Style Chicken", "price": 160.0},
    {"name": "Malbhi Barbecue (Half)", "cat": "Arabian Style Chicken", "price": 280.0},
    {"name": "Malbhi Barbecue (Full)", "cat": "Arabian Style Chicken", "price": 490.0},
    {"name": "Al Faham (Quarter)", "cat": "Arabian Style Chicken", "price": 160.0},
    {"name": "Al Faham (Half)", "cat": "Arabian Style Chicken", "price": 280.0},
    {"name": "Al Faham (Full)", "cat": "Arabian Style Chicken", "price": 490.0},
    {"name": "Al Faham Special (Half)", "cat": "Arabian Style Chicken", "price": 350.0},
    {"name": "Al Faham Special (Full)", "cat": "Arabian Style Chicken", "price": 600.0},
    {"name": "Pepper BBQ (Quarter)", "cat": "Arabian Style Chicken", "price": 160.0},
    {"name": "Pepper BBQ (Half)", "cat": "Arabian Style Chicken", "price": 280.0},
    {"name": "Pepper BBQ (Full)", "cat": "Arabian Style Chicken", "price": 490.0},
    {"name": "Grill Chicken (Quarter)", "cat": "Arabian Style Chicken", "price": 150.0},
    {"name": "Grill Chicken (Half)", "cat": "Arabian Style Chicken", "price": 240.0},
    {"name": "Grill Chicken (Full)", "cat": "Arabian Style Chicken", "price": 420.0},
    {"name": "Honey Chilli Al Faham (Quarter)", "cat": "Arabian Style Chicken", "price": 190.0},
    {"name": "Honey Chilli Al Faham (Half)", "cat": "Arabian Style Chicken", "price": 330.0},
    {"name": "Honey Chilli Al Faham (Full)", "cat": "Arabian Style Chicken", "price": 570.0},
    {"name": "Honey Al Faham (Quarter)", "cat": "Arabian Style Chicken", "price": 180.0},
    {"name": "Honey Al Faham (Half)", "cat": "Arabian Style Chicken", "price": 310.0},
    {"name": "Honey Al Faham (Full)", "cat": "Arabian Style Chicken", "price": 540.0},
    {"name": "Masala Shawaya (Quarter)", "cat": "Arabian Style Chicken", "price": 170.0},
    {"name": "Masala Shawaya (Half)", "cat": "Arabian Style Chicken", "price": 280.0},
    {"name": "Masala Shawaya (Full)", "cat": "Arabian Style Chicken", "price": 490.0},

    # 5. Mutton Gravy[cite: 5]
    {"name": "Mutton Masala", "cat": "Mutton Gravy", "price": 340.0},
    {"name": "Mutton Pepper Masala", "cat": "Mutton Gravy", "price": 350.0},
    {"name": "Mutton Kadai", "cat": "Mutton Gravy", "price": 360.0},
    {"name": "Mutton Pepper Fry / Dry", "cat": "Mutton Gravy", "price": 580.0},
    {"name": "Veg. Idam With Mutton", "cat": "Mutton Gravy", "price": 410.0},
    {"name": "Mutton Ghee Roast Dry", "cat": "Mutton Gravy", "price": 580.0},
    {"name": "Mutton Fry / Dry", "cat": "Mutton Gravy", "price": 580.0},
    {"name": "Butter Mutton Fry / Dry", "cat": "Mutton Gravy", "price": 580.0},
    {"name": "Mutton Kolhapuri", "cat": "Mutton Gravy", "price": 390.0},
    {"name": "Mutton Hyderabadi", "cat": "Mutton Gravy", "price": 390.0},
    {"name": "Mutton Mughalai", "cat": "Mutton Gravy", "price": 390.0},
    {"name": "Mutton Afghani", "cat": "Mutton Gravy", "price": 390.0},
    {"name": "Mutton Rogan Josh", "cat": "Mutton Gravy", "price": 410.0},

    # 6. Chicken Gravy[cite: 5]
    {"name": "Chicken Bhuna", "cat": "Chicken Gravy", "price": 280.0},
    {"name": "Butter Chicken", "cat": "Chicken Gravy", "price": 280.0},
    {"name": "Veg. Idam With Chicken", "cat": "Chicken Gravy", "price": 250.0},
    {"name": "Chicken Kadai", "cat": "Chicken Gravy", "price": 270.0},
    {"name": "Chicken Mughlai", "cat": "Chicken Gravy", "price": 280.0},
    {"name": "Chicken Pepper Masala", "cat": "Chicken Gravy", "price": 290.0},
    {"name": "Chicken Pahadi", "cat": "Chicken Gravy", "price": 290.0},
    {"name": "Chicken Patiala", "cat": "Chicken Gravy", "price": 290.0},
    {"name": "Chicken Afghani", "cat": "Chicken Gravy", "price": 290.0},
    {"name": "Chicken Kolhapuri", "cat": "Chicken Gravy", "price": 290.0},
    {"name": "Chicken Hyderabadi", "cat": "Chicken Gravy", "price": 290.0},
    {"name": "Chicken Ghee Roast", "cat": "Chicken Gravy", "price": 320.0},
    {"name": "Raidan Special Chi-Curry", "cat": "Chicken Gravy", "price": 320.0},

    # 7. Veg[cite: 5]
    {"name": "Veg. Idam", "cat": "Veg", "price": 180.0},
    {"name": "Idam Fasolia (Rajma)", "cat": "Veg", "price": 170.0},
    {"name": "Idam Barmia (Ladies Finger)", "cat": "Veg", "price": 140.0},
    {"name": "Aloo Gobi Mutter", "cat": "Veg", "price": 140.0},
    {"name": "Chana Masala", "cat": "Veg", "price": 140.0},
    {"name": "Green Peas Masala", "cat": "Veg", "price": 140.0},
    {"name": "Mix Veg.", "cat": "Veg", "price": 130.0},
    {"name": "Paneer Masala", "cat": "Veg", "price": 190.0},
    {"name": "Paneer Kolhapuri", "cat": "Veg", "price": 190.0},
    {"name": "Paneer Butter Masala", "cat": "Veg", "price": 190.0},
    {"name": "Mutter Paneer", "cat": "Veg", "price": 190.0},
    {"name": "Paneer Kadai", "cat": "Veg", "price": 190.0},
    {"name": "Veg. Kadai", "cat": "Veg", "price": 190.0},
    {"name": "Paneer Pepper Masala", "cat": "Veg", "price": 190.0},
    {"name": "Mushroom Masala", "cat": "Veg", "price": 180.0},
    {"name": "Mushroom Pepper Masala", "cat": "Veg", "price": 190.0},
    {"name": "Baby Corn Masala", "cat": "Veg", "price": 190.0},

    # 8. Egg[cite: 5]
    {"name": "Egg Masala", "cat": "Egg", "price": 120.0},
    {"name": "Egg Pepper Masala", "cat": "Egg", "price": 130.0},
    {"name": "Egg Bhurji", "cat": "Egg", "price": 100.0},
    {"name": "Egg Bhurji Masala", "cat": "Egg", "price": 130.0},
    {"name": "Egg Chilli", "cat": "Egg", "price": 130.0},
    {"name": "Egg Roast", "cat": "Egg", "price": 130.0},
    {"name": "Omelette", "cat": "Egg", "price": 70.0},
    {"name": "Boiled Egg", "cat": "Egg", "price": 20.0},

    # 9. Veg Dry and Gravy[cite: 5]
    {"name": "Gobi Chilli (Dry)", "cat": "Veg Dry and Gravy", "price": 160.0},
    {"name": "Gobi Chilli (Gravy)", "cat": "Veg Dry and Gravy", "price": 180.0},
    {"name": "Gobi Manchurian (Dry)", "cat": "Veg Dry and Gravy", "price": 160.0},
    {"name": "Gobi Manchurian (Gravy)", "cat": "Veg Dry and Gravy", "price": 180.0},
    {"name": "Gobi 65 (Dry)", "cat": "Veg Dry and Gravy", "price": 160.0},
    {"name": "Gobi 65 (Gravy)", "cat": "Veg Dry and Gravy", "price": 180.0},
    {"name": "Paneer Chilli (Dry)", "cat": "Veg Dry and Gravy", "price": 180.0},
    {"name": "Paneer Chilli (Gravy)", "cat": "Veg Dry and Gravy", "price": 200.0},
    {"name": "Mushroom Chilli (Dry)", "cat": "Veg Dry and Gravy", "price": 180.0},
    {"name": "Mushroom Chilli (Gravy)", "cat": "Veg Dry and Gravy", "price": 200.0},
    {"name": "Mushroom Manchurian (Dry)", "cat": "Veg Dry and Gravy", "price": 180.0},
    {"name": "Mushroom Manchurian (Gravy)", "cat": "Veg Dry and Gravy", "price": 200.0},
    {"name": "Mushroom 65", "cat": "Veg Dry and Gravy", "price": 190.0},
    {"name": "Baby Corn Pepper Fry", "cat": "Veg Dry and Gravy", "price": 190.0},

    # 10. Sides[cite: 5]
    {"name": "Mutton Murtabak", "cat": "Sides", "price": 280.0},
    {"name": "Chicken Murtabak", "cat": "Sides", "price": 230.0},
    {"name": "Banana Murtabak", "cat": "Sides", "price": 130.0},
    {"name": "Cheese Murtabak", "cat": "Sides", "price": 160.0},

    # 11. Dal[cite: 5]
    {"name": "Dal Fry", "cat": "Dal", "price": 140.0},
    {"name": "Dal Kolhapuri", "cat": "Dal", "price": 150.0},
    {"name": "Dal Tadka", "cat": "Dal", "price": 150.0},
    {"name": "Dal Butter Fry", "cat": "Dal", "price": 160.0},
    {"name": "Dal Punjabi", "cat": "Dal", "price": 150.0},

    # 12. Tandoor[cite: 5]
    {"name": "Tandoori Chicken (Half)", "cat": "Tandoor", "price": 250.0},
    {"name": "Tandoori Chicken (Full)", "cat": "Tandoor", "price": 470.0},
    {"name": "Kalmi Kabab (2 Pieces)", "cat": "Tandoor", "price": 200.0},
    {"name": "Kalmi Kabab (4 Pieces)", "cat": "Tandoor", "price": 380.0},
    {"name": "Tandoori Platter (8 Pieces)", "cat": "Tandoor", "price": 610.0},
    {"name": "Tandoori Kabab (8 Pieces)", "cat": "Tandoor", "price": 390.0},
    {"name": "Reshmi Kabab (8 Pieces)", "cat": "Tandoor", "price": 400.0},
    {"name": "Chicken Tikka (8 Pieces)", "cat": "Tandoor", "price": 380.0},
    {"name": "Malai Tikka (8 Pieces)", "cat": "Tandoor", "price": 380.0},
    {"name": "Paneer Tikka (8 Pieces)", "cat": "Tandoor", "price": 260.0},
    {"name": "Mix Platter (12 Pieces)", "cat": "Tandoor", "price": 860.0},
    {"name": "Hariyali Kabab (8 Pieces)", "cat": "Tandoor", "price": 360.0},
    {"name": "Malai Paneer Tikka (8 Pieces)", "cat": "Tandoor", "price": 300.0},
    {"name": "Raidan Spl. Platter (20 Pieces)", "cat": "Tandoor", "price": 1360.0},
    {"name": "Chicken Sheek Kabab (4 Pieces)", "cat": "Tandoor", "price": 200.0},
    {"name": "Chicken Sheek Kabab (8 Pieces)", "cat": "Tandoor", "price": 346.0},

    # 13. Breads[cite: 5]
    {"name": "Tandoori Roti", "cat": "Breads", "price": 40.0},
    {"name": "Butter Roti", "cat": "Breads", "price": 45.0},
    {"name": "Rumali Roti", "cat": "Breads", "price": 45.0},
    {"name": "Plain Naan", "cat": "Breads", "price": 45.0},
    {"name": "Lacha Paratha", "cat": "Breads", "price": 55.0},
    {"name": "Aloo Paratha", "cat": "Breads", "price": 65.0},
    {"name": "Butter Kulcha", "cat": "Breads", "price": 55.0},
    {"name": "Butter Naan", "cat": "Breads", "price": 55.0},
    {"name": "Plain Kulcha", "cat": "Breads", "price": 45.0},
    {"name": "Masala Kulcha", "cat": "Breads", "price": 55.0},
    {"name": "Cheese Garlic Naan", "cat": "Breads", "price": 65.0},
    {"name": "Paneer Kulcha", "cat": "Breads", "price": 65.0},
    {"name": "Garlic Naan", "cat": "Breads", "price": 55.0},
    {"name": "Tawa Chapathi", "cat": "Breads", "price": 30.0},
    {"name": "Phulka", "cat": "Breads", "price": 40.0},
    {"name": "Kerala Parotta", "cat": "Breads", "price": 40.0},
    {"name": "Raidan Oven Khuboos", "cat": "Breads", "price": 15.0},
    {"name": "Selon Pratha", "cat": "Breads", "price": 40.0},
    {"name": "Coin Pratha", "cat": "Breads", "price": 40.0},
    {"name": "Wheat Pratha", "cat": "Breads", "price": 45.0},

    # 14. Fried Rice and Noddles[cite: 5]
    {"name": "Veg. Fried Rice", "cat": "Fried Rice and Noddles", "price": 130.0},
    {"name": "Egg Fried Rice", "cat": "Fried Rice and Noddles", "price": 160.0},
    {"name": "Chicken Fried Rice", "cat": "Fried Rice and Noddles", "price": 180.0},
    {"name": "Mutton Fried Rice", "cat": "Fried Rice and Noddles", "price": 260.0},
    {"name": "Mushroom Fried Rice", "cat": "Fried Rice and Noddles", "price": 180.0},
    {"name": "Paneer Fried Rice", "cat": "Fried Rice and Noddles", "price": 190.0},
    {"name": "Mixed Fried Rice", "cat": "Fried Rice and Noddles", "price": 310.0},
    {"name": "Veg. Noodles", "cat": "Fried Rice and Noddles", "price": 160.0},
    {"name": "Chicken Noodles", "cat": "Fried Rice and Noddles", "price": 190.0},
    {"name": "Egg Noodles", "cat": "Fried Rice and Noddles", "price": 180.0},
    {"name": "Mixed Noodles", "cat": "Fried Rice and Noddles", "price": 310.0},
    {"name": "Paneer Noodles", "cat": "Fried Rice and Noddles", "price": 200.0},
    {"name": "Schezwan Veg. Fried Rice", "cat": "Fried Rice and Noddles", "price": 170.0},
    {"name": "Schezwan Chi-Fried Rice", "cat": "Fried Rice and Noddles", "price": 210.0},
    {"name": "Schezwan Egg Fried Rice", "cat": "Fried Rice and Noddles", "price": 190.0},
    {"name": "Schezwan Veg. Noodles", "cat": "Fried Rice and Noddles", "price": 180.0},
    {"name": "Schezwan Egg Noodles", "cat": "Fried Rice and Noddles", "price": 190.0},
    {"name": "Schezwan Chicken Noodles", "cat": "Fried Rice and Noddles", "price": 200.0},
    {"name": "Schezwan Mixed Noodles", "cat": "Fried Rice and Noddles", "price": 310.0},
    {"name": "Raidan Spl Chicken Fried Rice", "cat": "Fried Rice and Noddles", "price": 210.0},

    # 15. Chinese chi Boneless[cite: 5]
    {"name": "Chilli Chicken (Dry)", "cat": "Chinese chi Boneless", "price": 275.0},
    {"name": "Chilli Chicken (Gravy)", "cat": "Chinese chi Boneless", "price": 300.0},
    {"name": "Chicken Manchurian (Dry)", "cat": "Chinese chi Boneless", "price": 275.0},
    {"name": "Chicken Manchurian (Gravy)", "cat": "Chinese chi Boneless", "price": 300.0},
    {"name": "Chicken 65 (Dry)", "cat": "Chinese chi Boneless", "price": 275.0},
    {"name": "Chicken 65 (Gravy)", "cat": "Chinese chi Boneless", "price": 300.0},
    {"name": "Chicken Hot Garlic (Dry)", "cat": "Chinese chi Boneless", "price": 275.0},
    {"name": "Chicken Hot Garlic (Gravy)", "cat": "Chinese chi Boneless", "price": 300.0},
    {"name": "Ginger Chicken (Dry)", "cat": "Chinese chi Boneless", "price": 265.0},
    {"name": "Ginger Chicken (Gravy)", "cat": "Chinese chi Boneless", "price": 285.0},
    {"name": "Garlic Chicken (Dry)", "cat": "Chinese chi Boneless", "price": 265.0},
    {"name": "Garlic Chicken (Gravy)", "cat": "Chinese chi Boneless", "price": 285.0},
    {"name": "Schezwan Chicken (Dry)", "cat": "Chinese chi Boneless", "price": 275.0},
    {"name": "Schezwan Chicken (Gravy)", "cat": "Chinese chi Boneless", "price": 300.0},
    {"name": "Chicken Kabab (5 Pcs)", "cat": "Chinese chi Boneless", "price": 190.0},
    {"name": "Chicken Kabab (10 Pcs)", "cat": "Chinese chi Boneless", "price": 350.0},
    {"name": "Singapore Chicken (Dry)", "cat": "Chinese chi Boneless", "price": 275.0},
    {"name": "Singapore Chicken (Gravy)", "cat": "Chinese chi Boneless", "price": 300.0},
    {"name": "Crispy Chicken", "cat": "Chinese chi Boneless", "price": 285.0},
    {"name": "Hunan Chicken", "cat": "Chinese chi Boneless", "price": 285.0},
    {"name": "Chicken 555 (Spicy)", "cat": "Chinese chi Boneless", "price": 275.0},
    {"name": "Chicken Lolipop (8 Pieces)", "cat": "Chinese chi Boneless", "price": 300.0},
    {"name": "Chicken Pepper Dry / Fry", "cat": "Chinese chi Boneless", "price": 300.0},
    {"name": "Sweet & Sour Chicken", "cat": "Chinese chi Boneless", "price": 265.0},
    {"name": "Lemon Chicken", "cat": "Chinese chi Boneless", "price": 265.0},
    {"name": "Chicken Lolipop Manchurian", "cat": "Chinese chi Boneless", "price": 340.0},

    # 16. Fish[cite: 5]
    {"name": "Fish Barbecue (Seasonal)", "cat": "Fish", "price": 0.0},
    {"name": "Fish Fry (Seasonal)", "cat": "Fish", "price": 0.0},
    {"name": "Fish Tikka (Seasonal)", "cat": "Fish", "price": 0.0},
    {"name": "Fish Madfoona (Seasonal)", "cat": "Fish", "price": 0.0},
    {"name": "Fish Tawa Fry (Seasonal)", "cat": "Fish", "price": 0.0},
    {"name": "Fish Mandi (Seasonal)", "cat": "Fish", "price": 0.0},
    {"name": "Fish Curry Kerala Style (Seasonal)", "cat": "Fish", "price": 0.0},
    {"name": "Prawns Fry (Seasonal)", "cat": "Fish", "price": 0.0},
    {"name": "Prawns Masala (Seasonal)", "cat": "Fish", "price": 0.0},
    {"name": "Golden Fried Prawns (Seasonal)", "cat": "Fish", "price": 0.0},
    {"name": "Prawns Barbecue (Seasonal)", "cat": "Fish", "price": 0.0},
    {"name": "Prawns Manchurian (Seasonal)", "cat": "Fish", "price": 0.0},
    {"name": "Prawns Chilli (Seasonal)", "cat": "Fish", "price": 0.0},
    {"name": "Prawns 65 (Seasonal)", "cat": "Fish", "price": 0.0},
    {"name": "Squid Tava (Seasonal)", "cat": "Fish", "price": 0.0},

    # 17. soups[cite: 5]
    {"name": "Arabian Chicken Soup", "cat": "soups", "price": 160.0},
    {"name": "Arabian Mutton Soup", "cat": "soups", "price": 180.0},
    {"name": "Arabian Veg Soup", "cat": "soups", "price": 130.0},
    {"name": "Manchow Veg Soup", "cat": "soups", "price": 130.0},
    {"name": "Clear Veg Soup", "cat": "soups", "price": 110.0},
    {"name": "Clear Non Veg Soup", "cat": "soups", "price": 110.0},
    {"name": "Chicken Pepper Soup", "cat": "soups", "price": 150.0},
    {"name": "Mutton Shorba", "cat": "soups", "price": 180.0},
    {"name": "Hot & Sour Soup", "cat": "soups", "price": 140.0},
    {"name": "Chicken Clear Soup", "cat": "soups", "price": 150.0},
    {"name": "Chicken Manchow Soup", "cat": "soups", "price": 160.0},
    {"name": "Tomato Soup", "cat": "soups", "price": 160.0},
    {"name": "Cream Style Chicken Soup", "cat": "soups", "price": 180.0},
    {"name": "Cream Style Manchow Soup", "cat": "soups", "price": 170.0},
    {"name": "Sweet Corn Chicken Soup", "cat": "soups", "price": 180.0},
    {"name": "Sweet Corn Veg. Soup", "cat": "soups", "price": 160.0},

    # 18. Combo[cite: 5]
    {"name": "Combo 1 (1 Pc Chicken + Fries + 1 Bun + 200ml Pepsi)", "cat": "Combo", "price": 200.0},
    {"name": "Combo 2 (2 Pcs Chicken + Fries + 1 Bun + 200ml Pepsi)", "cat": "Combo", "price": 340.0},
    {"name": "Combo 6 (6 Pcs Chicken + Fries + 3 Buns + 500ml Pepsi + Garlic)", "cat": "Combo", "price": 750.0},
    {"name": "Combo 12 (12 Pcs Chicken + Fries + 5 Buns + 1L Pepsi + Garlic)", "cat": "Combo", "price": 1350.0},

    # 19. Rolls[cite: 5]
    {"name": "Egg Omelette Roll (Paratha/Kubus)", "cat": "Rolls", "price": 110.0},
    {"name": "Chicken Roll (Paratha/Kubus)", "cat": "Rolls", "price": 140.0},
    {"name": "Paneer Roll (Paratha/Kubus)", "cat": "Rolls", "price": 130.0},
    {"name": "Chicken Strips Roll", "cat": "Rolls", "price": 150.0},
    {"name": "Chicken Strips + Omelette Roll", "cat": "Rolls", "price": 150.0},
    {"name": "Chicken Fried Roll", "cat": "Rolls", "price": 140.0},
    {"name": "Chicken Corn Cheese Roll", "cat": "Rolls", "price": 170.0},
    {"name": "Sarook Chicken (Paratha)", "cat": "Rolls", "price": 170.0},
    {"name": "Nuggets Paratha", "cat": "Rolls", "price": 150.0},
    {"name": "Falafil Sliced Egg+Cheese", "cat": "Rolls", "price": 150.0},
    {"name": "Falafil Sliced Egg", "cat": "Rolls", "price": 110.0},
    {"name": "Keema Rolls (Paratha/Kubus)", "cat": "Rolls", "price": 130.0},
    {"name": "Chopped Hot Dog Combo", "cat": "Rolls", "price": 160.0},
    {"name": "Falafil Sandwich", "cat": "Rolls", "price": 110.0},
    {"name": "Club Chicken (Special)", "cat": "Rolls", "price": 190.0},
    {"name": "Arabian Club", "cat": "Rolls", "price": 190.0},
    {"name": "Chicken Hot Peal Roll", "cat": "Rolls", "price": 140.0},
    {"name": "Chicken Tikka Roll", "cat": "Rolls", "price": 150.0},
    {"name": "Malai Kabab Roll", "cat": "Rolls", "price": 150.0},

    # 20. Shawarma[cite: 5]
    {"name": "Shawarma Roll", "cat": "Shawarma", "price": 100.0},
    {"name": "Jumbo Shawarma", "cat": "Shawarma", "price": 160.0},
    {"name": "Plate Shawarma", "cat": "Shawarma", "price": 190.0},
    {"name": "Plate Shawarma Special", "cat": "Shawarma", "price": 280.0},
    {"name": "Only Chicken Shawarma Roll", "cat": "Shawarma", "price": 130.0},
    {"name": "Only Chicken Plate", "cat": "Shawarma", "price": 330.0},
    {"name": "Only Chi-Shawarma Jumbo", "cat": "Shawarma", "price": 190.0},
    {"name": "Only Chi-Shawarma Hummus", "cat": "Shawarma", "price": 220.0},
    {"name": "Hummus Shawarma", "cat": "Shawarma", "price": 140.0},
    {"name": "Hummus Plate Shawarma", "cat": "Shawarma", "price": 220.0},

    # 21. SAlad[cite: 5]
    {"name": "Green Salad (Small)", "cat": "SAlad", "price": 110.0},
    {"name": "Green Salad (Large)", "cat": "SAlad", "price": 150.0},
    {"name": "Hummus (Small)", "cat": "SAlad", "price": 95.0},
    {"name": "Hummus (Large)", "cat": "SAlad", "price": 140.0},
    {"name": "Garlic Dip (Small)", "cat": "SAlad", "price": 85.0},
    {"name": "Garlic Dip (Large)", "cat": "SAlad", "price": 130.0},
    {"name": "Fatoush Salad", "cat": "SAlad", "price": 170.0},
    {"name": "Cucumber Salad", "cat": "SAlad", "price": 85.0},
    {"name": "Onion Salad", "cat": "SAlad", "price": 75.0},

    # 22. Fried chi an dBurgers[cite: 5]
    {"name": "Master Box", "cat": "Fried chi an dBurgers", "price": 260.0},
    {"name": "Fried Burger Meal", "cat": "Fried chi an dBurgers", "price": 275.0},
    {"name": "Veg Burger Meal", "cat": "Fried chi an dBurgers", "price": 190.0},
    {"name": "Two Piece Chicken", "cat": "Fried chi an dBurgers", "price": 210.0},
    {"name": "Four Piece Chicken", "cat": "Fried chi an dBurgers", "price": 380.0},
    {"name": "Fried Chi-Bucket (6 Piece)", "cat": "Fried chi an dBurgers", "price": 550.0},
    {"name": "Fried Chi-Bucket (8 Piece)", "cat": "Fried chi an dBurgers", "price": 695.0},
    {"name": "Fried Chi-Bucket (12 Piece)", "cat": "Fried chi an dBurgers", "price": 995.0},
    {"name": "Fried Chicken Burger", "cat": "Fried chi an dBurgers", "price": 160.0},
    {"name": "Jalapeno Burger", "cat": "Fried chi an dBurgers", "price": 150.0},
    {"name": "Chicken Hot Peal Burger", "cat": "Fried chi an dBurgers", "price": 140.0},
    {"name": "Chicken Burger", "cat": "Fried chi an dBurgers", "price": 150.0},
    {"name": "Fried Burger (Veg)", "cat": "Fried chi an dBurgers", "price": 140.0},
    {"name": "Chicken Boneless Strips", "cat": "Fried chi an dBurgers", "price": 160.0},
    {"name": "Lollipop (4 Pieces)", "cat": "Fried chi an dBurgers", "price": 150.0},
    {"name": "Lollipop (8 Pieces)", "cat": "Fried chi an dBurgers", "price": 280.0},
    {"name": "Chicken Corn Box", "cat": "Fried chi an dBurgers", "price": 190.0},
    {"name": "French Fries (Small)", "cat": "Fried chi an dBurgers", "price": 130.0},
    {"name": "French Fries (Medium)", "cat": "Fried chi an dBurgers", "price": 160.0},
    {"name": "French Fries (Large)", "cat": "Fried chi an dBurgers", "price": 190.0},
    {"name": "Smiles (10 Pieces)", "cat": "Fried chi an dBurgers", "price": 130.0},
    {"name": "Savoury Wedges", "cat": "Fried chi an dBurgers", "price": 130.0},
    {"name": "Nuggets (8 Pieces)", "cat": "Fried chi an dBurgers", "price": 150.0},
    {"name": "Crab (4 Pieces)", "cat": "Fried chi an dBurgers", "price": 150.0},
    {"name": "Crab (8 Pieces)", "cat": "Fried chi an dBurgers", "price": 275.0},

    # 23. Arabian Desserts[cite: 5]
    {"name": "Busboosa Special", "cat": "Arabian Desserts", "price": 100.0},
    {"name": "Tender Coconut Pudding", "cat": "Arabian Desserts", "price": 80.0},
    {"name": "Mango Pudding", "cat": "Arabian Desserts", "price": 80.0},
    {"name": "Kunafa Cream", "cat": "Arabian Desserts", "price": 290.0},
    {"name": "Kunafa Cheese", "cat": "Arabian Desserts", "price": 320.0},

    # 24. Fresh fruit Creams[cite: 5]
    {"name": "Mix Fruit Cream", "cat": "Fresh fruit Creams", "price": 170.0},
    {"name": "Chickoo Cream", "cat": "Fresh fruit Creams", "price": 150.0},
    {"name": "Custard Apple Cream", "cat": "Fresh fruit Creams", "price": 170.0},
    {"name": "Fresh Strawberry Cream", "cat": "Fresh fruit Creams", "price": 170.0},
    {"name": "Dry Fruit Cream", "cat": "Fresh fruit Creams", "price": 190.0},
    {"name": "Mango Cream", "cat": "Fresh fruit Creams", "price": 150.0},
    {"name": "Apple Cream", "cat": "Fresh fruit Creams", "price": 150.0},
    {"name": "Banana Cream", "cat": "Fresh fruit Creams", "price": 140.0},

    # 25. Falooda[cite: 5]
    {"name": "Tutti Fruity", "cat": "Falooda", "price": 110.0},
    {"name": "Fruit Salad", "cat": "Falooda", "price": 120.0},
    {"name": "Raidan Special Falooda", "cat": "Falooda", "price": 150.0},
    {"name": "Arabian Falooda", "cat": "Falooda", "price": 180.0},
    {"name": "Royal Falooda", "cat": "Falooda", "price": 160.0},
    {"name": "Banana Pot", "cat": "Falooda", "price": 160.0},
    {"name": "Mini Falooda", "cat": "Falooda", "price": 130.0},
    {"name": "Ice Cream 3 in 1", "cat": "Falooda", "price": 150.0},
    {"name": "Fruit Plate", "cat": "Falooda", "price": 130.0},
    {"name": "Vanilla / Strawberry Scoop", "cat": "Falooda", "price": 50.0},
    {"name": "Chocolate Ice Cream", "cat": "Falooda", "price": 60.0},
    {"name": "Butterscotch Ice Cream", "cat": "Falooda", "price": 60.0},
    {"name": "Black Current Ice Cream", "cat": "Falooda", "price": 60.0},
    {"name": "Mango / Pista Ice Cream", "cat": "Falooda", "price": 60.0},

    # 26. Crushes[cite: 5]
    {"name": "Blue Berry Crush", "cat": "Crushes", "price": 90.0},
    {"name": "Kiwi Crush", "cat": "Crushes", "price": 90.0},
    {"name": "Orange Relaxer", "cat": "Crushes", "price": 90.0},
    {"name": "Lichi Like", "cat": "Crushes", "price": 90.0},
    {"name": "Verjin Mojito", "cat": "Crushes", "price": 100.0},

    # 27. DEsert[cite: 5]
    {"name": "Fruty Falooda", "cat": "DEsert", "price": 150.0},
    {"name": "Royal Butterscotch Sundae", "cat": "DEsert", "price": 150.0},
    {"name": "Royal Falooda (Desert)", "cat": "DEsert", "price": 130.0},
    {"name": "Chocolate Fudge", "cat": "DEsert", "price": 180.0},
    {"name": "Raidan Special Desert", "cat": "DEsert", "price": 200.0},
    {"name": "Mango Falooda", "cat": "DEsert", "price": 130.0},
    {"name": "Bombai Flooda", "cat": "DEsert", "price": 180.0},
    {"name": "Puttu Ice Cream", "cat": "DEsert", "price": 250.0},
    {"name": "Choice of Ice Cream", "cat": "DEsert", "price": 60.0},

    # 28. FResh juices and Milk Shakes[cite: 5]
    {"name": "Muasambi Fresh Juice", "cat": "FResh juices and Milk Shakes", "price": 70.0},
    {"name": "Watermelon Juice", "cat": "FResh juices and Milk Shakes", "price": 60.0},
    {"name": "Ginger & Lemon With Mint", "cat": "FResh juices and Milk Shakes", "price": 60.0},
    {"name": "Orange Fresh Juice", "cat": "FResh juices and Milk Shakes", "price": 80.0},
    {"name": "Pomegranate Fresh Juice", "cat": "FResh juices and Milk Shakes", "price": 110.0},
    {"name": "Mango Fresh Juice", "cat": "FResh juices and Milk Shakes", "price": 90.0},
    {"name": "Apple Fresh Juice", "cat": "FResh juices and Milk Shakes", "price": 130.0},
    {"name": "Arabian Pulpy Special", "cat": "FResh juices and Milk Shakes", "price": 100.0},
    {"name": "Grape Juice", "cat": "FResh juices and Milk Shakes", "price": 80.0},
    {"name": "Papaya Juice", "cat": "FResh juices and Milk Shakes", "price": 80.0},
    {"name": "Carrot Fresh Juice", "cat": "FResh juices and Milk Shakes", "price": 100.0},
    {"name": "Pineapple Juice", "cat": "FResh juices and Milk Shakes", "price": 70.0},
    {"name": "Muskmelon Juice", "cat": "FResh juices and Milk Shakes", "price": 70.0},
    {"name": "Lime with Mint", "cat": "FResh juices and Milk Shakes", "price": 50.0},
    {"name": "Lemon With Soda", "cat": "FResh juices and Milk Shakes", "price": 50.0},
    {"name": "Plain Lemon Juice", "cat": "FResh juices and Milk Shakes", "price": 50.0},
    {"name": "Orange / Carrot Mix", "cat": "FResh juices and Milk Shakes", "price": 110.0},
    {"name": "Mango / Carrot Mix", "cat": "FResh juices and Milk Shakes", "price": 110.0},
    {"name": "Mango / Butter Mix", "cat": "FResh juices and Milk Shakes", "price": 120.0},
    {"name": "Guava / Carrot Mix", "cat": "FResh juices and Milk Shakes", "price": 110.0},
    {"name": "Orange / Pineapple Mix", "cat": "FResh juices and Milk Shakes", "price": 100.0},
    {"name": "Pineapple Lime", "cat": "FResh juices and Milk Shakes", "price": 80.0},
    {"name": "Grape Lime", "cat": "FResh juices and Milk Shakes", "price": 80.0},
    {"name": "Mojito Fresh", "cat": "FResh juices and Milk Shakes", "price": 120.0},
    {"name": "Mango Banana Shikuf", "cat": "FResh juices and Milk Shakes", "price": 110.0},
    {"name": "Titanic Special", "cat": "FResh juices and Milk Shakes", "price": 110.0},
    {"name": "Abbadi", "cat": "FResh juices and Milk Shakes", "price": 120.0},
    {"name": "Abood", "cat": "FResh juices and Milk Shakes", "price": 90.0},
    {"name": "Dry Fruit Milk Shake", "cat": "FResh juices and Milk Shakes", "price": 170.0},
    {"name": "Cocktail Milk Shake", "cat": "FResh juices and Milk Shakes", "price": 120.0},
    {"name": "Strawberry Fresh Milk Shake", "cat": "FResh juices and Milk Shakes", "price": 140.0},
    {"name": "Apple Milk Shake", "cat": "FResh juices and Milk Shakes", "price": 140.0},
    {"name": "Custard Apple Milk Shake", "cat": "FResh juices and Milk Shakes", "price": 150.0},
    {"name": "Vanilla Milk Shake", "cat": "FResh juices and Milk Shakes", "price": 90.0},
    {"name": "Pista Milk Shake", "cat": "FResh juices and Milk Shakes", "price": 90.0},
    {"name": "Mango Milk Shake", "cat": "FResh juices and Milk Shakes", "price": 120.0},
    {"name": "Guava Milk Shake", "cat": "FResh juices and Milk Shakes", "price": 100.0},
    {"name": "Avocado with Honey Shake", "cat": "FResh juices and Milk Shakes", "price": 170.0},
    {"name": "Butter Fruit Shake", "cat": "FResh juices and Milk Shakes", "price": 140.0},
    {"name": "Chocolate Milk Shake", "cat": "FResh juices and Milk Shakes", "price": 100.0},
    {"name": "Chickoo Milk Shake", "cat": "FResh juices and Milk Shakes", "price": 100.0},
    {"name": "Banana Milk Shake", "cat": "FResh juices and Milk Shakes", "price": 80.0},
    {"name": "Sharjah Shake", "cat": "FResh juices and Milk Shakes", "price": 110.0},
    {"name": "Sweet Lassi", "cat": "FResh juices and Milk Shakes", "price": 80.0},
    {"name": "Salt Lassi", "cat": "FResh juices and Milk Shakes", "price": 80.0},
    {"name": "Mango Lassi", "cat": "FResh juices and Milk Shakes", "price": 100.0},
    {"name": "Dry Fruit Lassi", "cat": "FResh juices and Milk Shakes", "price": 140.0},
    {"name": "Mix Fruit Lassi", "cat": "FResh juices and Milk Shakes", "price": 140.0}
]

def seed_database():
    print("Purging existing menu records...")
    db.query(MenuItem).delete()

    print(f"Seeding {len(RAIDAN_EXACT_MENU)} Raidan items with custom sections...")
    for item in RAIDAN_EXACT_MENU:
        db.add(MenuItem(
            name=item["name"],
            cat=item["cat"],
            price=item["price"],
            avail=True
        ))
    db.commit()
    print("Seeding complete!")

if __name__ == "__main__":
    seed_database()